<?php
	const WEBSITE = "localhost/example";
	const BASE_SITE = "https://".WEBSITE."/";
	const BASE_URL = BASE_SITE."index.php?url=";
	const INDEX = BASE_SITE."index.php?url=";
	const SOFT = BASE_SITE."soft.php?url=";
	const TYPE = "blog";
	const EMAIL = "isratahamedsabbir@gmail.com";
	const EMAIL_ADDRESS = "isratahamedsabbir@gmail.com";
	const PRIMARY_ADDRESS = "isratahamedsabbir@gmail.com";
	const MOBILE_NUMBER = "01775567493";
	const BACKEND = BASE_URL."backend";
	const BACKEND_HOME = BASE_URL."backend";
	const DASHBOARD = BASE_URL."backend";
	const BASE_CLASS = "theme_example";
	const FRONTEND = BASE_URL.BASE_CLASS;
	const FRONTEND_HOME = BASE_URL.BASE_CLASS;
	const HOME = BASE_URL.BASE_CLASS;
	const THEME = "example";
	const DATATABLE = "example_datatable";
	const ROOT_FOLDER = "";
	const BASE_FOLDER = ROOT_FOLDER."/"."extra/";
	const UPLOAD_FOLDER = "extra/resources/uploads/";
	const STORAGE = "extra/storage/";
	const PRODUCT_ID = "huhfwy476523cfhdfhdfhtjhh2u745y2734";
    const USER_NAME = "sabbir";
    const USER_PASSWORD = "1928374655";
    const TOKEN = "sabbir1928374655";
?>